matrix:
  include:
    - language: python
      python: 2.7

      service:
        - postgresql

      before_install:
        - export APP_SETTINGS="server.config.TestingConfig"

      install:
        - pip install -r backend/requirements.txt

      before_script:
        - psql -c 'create database foodtracker_test;' -U postgres
        - psql -d foodtracker_test -c 'create extension cube;' -U postgres
        - psql -d foodtracker_test -c 'create extension earthdistance;' -U postgres
        - python backend/manager.py create_db

      script:
        - cd backend; ./presubmit.sh

      after_failure:
        - git diff --name-only
        - git diff

    - language: node_js

      node_js: 6

      install:
        - cd frontend; npm install

      script:
        - npm run compile

notifications:
    email:
        recipients:
            - rj2394@columbia.edu
            - lx2180@columbia.edu
        on_success: never
        on_failure: never
